usethis::create_package(getwd())
#
usethis::use_dev_package("ready4agents")
usethis::use_dev_package("ready4epi")
usethis::use_dev_package("ready4s4")
usethis::use_dev_package("ready4utils")
usethis::use_package("dplyr")
usethis::use_package("googleway")
usethis::use_package("httr")
usethis::use_package("invgamma")
usethis::use_package("jsonlite")
usethis::use_package("lubridate")
usethis::use_package("magrittr")
usethis::use_package("osrm")
usethis::use_package("purrr")
# usethis::use_package("readxl")
usethis::use_package("rlang")
#usethis::use_package("seplyr")
usethis::use_package("sf")
usethis::use_package("stats")
usethis::use_package("stringr")
usethis::use_package("tibble")
# usethis::use_package("units")
devtools::document()
