## Script to create the Make Classes Table from which S4 classes will be made.
##
## 1. Prerequisites
##    None
##
## 2. Make the ready4_class_make_tb object summarising the metadata about the S3 classes that we wish to create and export with this package.
s4_classes_to_make_tb <- dplyr::bind_rows(
  ready4class::make_pt_ready4_constructor(make_s3_lgl = FALSE,
                                              name_stub_chr = "lookup", # rename to sp_lups
                                              slots_ls = c("sp_abbreviations_lup","sp_import_lup","sp_data_pack_lup","sp_resolution_lup","sp_site_coord_lup","sp_starter_sf_lup","sp_uid_lup") %>% list() %>% list(),
                                              pt_ls = c("ready4_sp_abbreviations_lup","vicinity_raw","ready4_sp_data_pack_lup","vicinity_resolutions","vicinity_points","vicinity_templates","vicinity_identifiers") %>% list() %>% list(),
                                              class_desc_chr = "Look up tables to use throughout ready4 suite",
                                              parent_class_chr = NA_character_),
  ready4class::make_pt_ready4_constructor(make_s3_lgl = FALSE,
                                              name_stub_chr = "macro",
                                              class_desc_chr = "Macro level context",
                                              pt_ls = list(c("character","character","numeric","VicinityLookup","numeric","POSIXt","POSIXt")) %>% list(),
                                              slots_ls = list(c("global_region","country","country_bound_year","lookup_tb","crs_nbr","temporal_min", "temporal_max")) %>% list(),
                                              parent_class_chr = NA_character_,
                                              inc_clss_ls = list("VicinityLookup")),
  ready4class::make_pt_ready4_constructor(make_s3_lgl = FALSE,
                                              name_stub_chr = "meso_region",
                                              class_desc_chr = "Meso level context - region",
                                              pt_ls = list(c("character","character","numeric")) %>% list(),
                                              slots_ls = list(c("region_type","region","region_bound_year")) %>% list(),
                                              parent_class_chr = "VicinityMacro"),
  ready4class::make_pt_ready4_constructor(make_s3_lgl = FALSE,
                                              name_stub_chr = "meso_area",
                                              class_desc_chr = "Meso level context - area",
                                              pt_ls = list(c("character","character","numeric")) %>% list(),
                                              slots_ls = list(c("area_type","area","area_bound_year")) %>% list(),
                                              parent_class_chr = "VicinityMesoRegion"),
  ready4class::make_pt_ready4_constructor(make_s3_lgl = FALSE,
                                              name_stub_chr = "micro",
                                              class_desc_chr = "Micro level context",
                                              pt_ls = list(c("numeric","numeric","character")) %>% list(),
                                              slots_ls = list(c("geom_dist_km_cuts","travel_time_mins_cuts", "travel_mode")) %>% list(),
                                              parent_class_chr  = "VicinityMesoArea"),
  ready4class::make_pt_ready4_constructor(make_s3_lgl = FALSE,
                                              name_stub_chr = "profiled_area",
                                              class_desc_chr = "Information to create a profiled area object",
                                              pt_ls = list(c("character","logical", "numeric", "numeric", "numeric", "character","POSIXt")) %>% list(),
                                              slots_ls = list(c("features","use_coord_lup","geom_dist_limit_km", "drive_time_limit_mins", "nbr_bands", "data_year","data_ymds")) %>% list(),
                                              parent_class_chr = "VicinityMicro"),
  ready4class::make_pt_ready4_constructor(make_s3_lgl = FALSE,
                                              name_stub_chr = "env",
                                              slots_ls = c("st_data","env_sf","param_vals") %>% list() %>% list(),
                                              pt_ls = c("list","sf","tbl_df") %>% list() %>% list(),
                                              class_desc_chr = "Spatiotemporal environment",
                                              parent_class_chr = NA_character_),
    ready4class::make_pt_ready4_constructor(make_s3_lgl = FALSE,
                                                name_stub_chr = "sp_local",
                                                slots_ls = c("lup_tbs_r4") %>% list() %>% list(),
                                                pt_ls = c("VicinityLookup") %>% list() %>% list(),
                                                class_desc_chr = "Object defining data to be saved in local directory.",
                                                parent_class_chr = "Ready4useFiles"),
  ready4class::make_pt_ready4_constructor(make_s3_lgl = FALSE,
                                              name_stub_chr = "spRaw",
                                              slots_ls = c("lup_tbs_r4") %>% list() %>% list(),
                                              pt_ls = c("VicinityLookup") %>% list() %>% list(),
                                              class_desc_chr = "Object defining data to be saved in local directory in a raw (unprocessed) format.",
                                              parent_class_chr = "Ready4useRaw"),
  ready4class::make_pt_ready4_constructor(make_s3_lgl = FALSE,
                                              name_stub_chr = "spProcessed",
                                              slots_ls = c("lup_tbs_r4") %>% list() %>% list(),
                                              pt_ls = c("VicinityLookup") %>% list() %>% list(),
                                              class_desc_chr = "Object defining data to be saved in local directory in a processed (R) format.",
                                              parent_class_chr = "Ready4useProcessed")) %>%
  ready4class::ready4_constructor()

